shirts/config/routes.rb
Shirts::Application.routes.draw do

  root "shirts#index"

  resources :shirts

  

end

shirts/app/models/shirt.rb
class Shirt < ActiveRecord::Base
	def self.search_for(query)
		Shirt.where("name LIKE :query OR description LIKE :query", :query => "%#{query}%")
	end
end

shirts/app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
	def index
		if params[:q].present?
			@shirts = Shirt.search_for(params[:q])
		else
			@shirts = Shirt.all.order("created_at DESC")
		end
	end

	def new
		@shirt = Shirt.new
	end

	def create
		@shirt = Shirt.new(safe_shirt_params)
		logger.info(@shirt.inspect) 

		@shirt.save
		redirect_to root_path
	end

	def show
		@shirt = Shirt.find(params[:id])
	end

	def edit
		@shirt = Shirt.find(params[:id])
	end

	def update
		@shirt = Shirt.find(params[:id])
		@shirt.update(safe_shirt_params)

		redirect_to shirt_path(@shirt)
	end

	def destroy
		@shirt = Shirt.find(params[:id])
		@shirt.destroy

		redirect_to root_path
	end

	private

	def safe_shirt_params
		return params.require(:shirt).permit(:name, :description, :image)
	end
end

shirts/app/helpers/shirts_helper.rb
module ShirtsHelper
end

shirts/app/views/shirts/_form.html.erb
<%= form_for @shirt do |f| %>
	<div>
		<%= f.label :name, "Name of shirt" %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :description, "Description" %>
		<%= f.text_field :description %>
	</div>
	<div>
		<%= f.label :image, "Image Filename" %>
		<%= f.text_field :image %>
	</div>
	<%= f.submit "Create shirt" %>
<% end %>

shirts/app/views/shirts/edit.html.erb
<h1>Edit <%= @shirt.name %> Shirt</h1>

<%= render "shirts/form" %>
<img src="<%= image_path(@shirt.image) %>">

shirts/app/views/shirts/index.html.erb
<h1><a href="<%= root_path %>">Shirts!</a></h1>

<a href="<%= new_shirt_path %>">+ Add a shirt</a>
<br>

<%= form_tag "/", :method => :get do %>
	<%= text_field_tag :q, params[:q] %>
	<%= submit_tag "Find Shirts" %>
<% end %>
<ul>
	<!--each_with_index-->
	<% @shirts.each do |shirt| %>
		<li>
			<h2><a href="<%= shirt_path(shirt) %>"><%= shirt.name %></a></h2>
			<p><%= shirt.description %></p>
			<a href="<%= shirt_path(shirt) %>"><img src="<%= image_path(shirt.image) %>"></a>
			<a href="<%= edit_shirt_path(shirt) %>">Edit shirt</a>
		</li>
	<% end %>
</ul>

shirts/app/views/shirts/new.html.erb
<h1>Add a shirt</h1>
<!--new forms use form_for instead of form_tag-->
<!--render file path doesn't need to be that specific in this case, but doesn't hurt-->
<%= render "shirts/form" %>

shirts/app/views/shirts/show.html.erb
<h1><%= @shirt.name %></h1>
<p><%= @shirt.description %></p>
<img src="<%= image_path(@shirt.image) %>">
<a href="<%= edit_shirt_path(@shirt) %>">Edit shirt</a>

<%= button_to "Delete Shirt", shirt_path(@shirt), :method => :delete %>