games_on_rails/games_on_rails/config/routes.rb
GamesOnRails::Application.routes.draw do

  root "main#index"
  get 'about' => 'main#about'
  get 'how_it_works' => 'main#how_it_works'

  resources :secret_numbers
  resources :rock_paper_scissors

  

end

games_on_rails/games_on_rails/app/models/image.rb
class Image < ActiveRecord::Base
end

games_on_rails/games_on_rails/app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

  def about
  end

  def how_it_works
  end

end

#   	

games_on_rails/games_on_rails/app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController
	def index
		create_weapons
	end

	def show
		create_weapons
		@player_played = params[:id]
		@computer_played = @weapons.sample

		outcome = @beatings[@player_played][@computer_played]
		@result = outcome.to_s
	end

	private

	def create_weapons
		@weapons = ["rock", "paper", "scissors"]
		@beatings = {
			"rock" => {"rock" => :tie, "paper" => :lose, "scissors" => :win},
			"paper" => {"rock" => :win, "paper" => :tie, "scissors" => :lose},
			"scissors" => {"rock" => :lose, "paper" => :win, "scissors" => :tie}
		}
	end
end

games_on_rails/games_on_rails/app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
	def index
	end

	def show
		@chosenNumber = params[:id].to_i
		@secretNumber = rand(5) + 1
	end

end

games_on_rails/games_on_rails/app/helpers/rock_paper_scissors_helper.rb
module RockPaperScissorsHelper
end

games_on_rails/games_on_rails/app/helpers/secret_numbers_helper.rb
module SecretNumbersHelper
end

games_on_rails/games_on_rails/app/views/rock_paper_scissors/index.html.erb
<div class="row">
	<div class="span12">
		<h1>Welcome to Rock Paper Scissors!</h1>
		<p>To play the game, chosse a throw:</p>
	</div>
</div><!--end row-->
<div class="row">
	<div class="span4">
		<a href="<%= rock_paper_scissor_path("#{@weapons[0]}") %>"><img src="<%= image_path("rock_paper_scissors/#{@weapons[0]}.jpeg") %>">
		<h3><%= @weapons[0].capitalize %></h3></a>
	</div>
	<div class="span4">
		<a href="<%= rock_paper_scissor_path("#{@weapons[1]}") %>"><img src="<%= image_path("rock_paper_scissors/#{@weapons[1]}.jpeg") %>">
		<h3><%= @weapons[1].capitalize %></h3></a>
	</div>
	<div class="span4">
		<a href="<%= rock_paper_scissor_path("#{@weapons[2]}") %>"><img src="<%= image_path("rock_paper_scissors/#{@weapons[2]}.jpeg") %>">
		<h3><%= @weapons[2].capitalize %></h3></a>
	</div>
</div><!--end row-->

games_on_rails/games_on_rails/app/views/rock_paper_scissors/show.html.erb
<div class="row">
	<div class="span4 offset2">
		<p>You threw:</p>
		<img src="<%= image_path("rock_paper_scissors/#{@player_played}.jpeg") %>">
		<h3><%= @player_played %></h3>
	</div>
	<div class="span4">
		<p>Rails threw:</p>
		<img src="<%= image_path("rock_paper_scissors/#{@computer_played}.jpeg") %>">
		<h3><%= @computer_played %></h3>
	</div>

</div><!--end row-->

<div class="row">
	<div class="span12">
		<% if @result == "tie" %>
			<p>It's a tie!</p>
			<img src="<%= image_path("tie.jpg") %> ">
			<p><a href="<%= rock_paper_scissors_path %>">Play again.</a></p>
		<% elsif @result == "win" %>
			<p>You win!</p>
			<img src="<%= image_path("winner.gif") %> ">
			<p><a href="<%= rock_paper_scissors_path %>">Play again.</a></p>
		<% elsif @result == "lose" %>
			<p>You lose!</p>
			<img src="<%= image_path("loser.gif") %> ">
			<p><a href="<%= rock_paper_scissors_path %>">Try again.</a></p>
		<% end %>
	</div>
	<p><%= @outcome %></p>
</div><!--end row-->