stuff_finder/config/routes.rb
StuffFinder::Application.routes.draw do
  devise_for :users

  root "main#index"
  resources :categories
  resources :classifieds

  

end

stuff_finder/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :classifieds
end

stuff_finder/app/models/classified.rb
class Classified < ActiveRecord::Base
	belongs_to :category
	belongs_to :user

	mount_uploader :image, ImageUploader
end

stuff_finder/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

stuff_finder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

stuff_finder/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
	end

	def show
		@category = Category.find(params[:id])
		@classifieds = Classified.where("category_id = #{@category.id}" )
	end
end

stuff_finder/app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController

	before_action :authenticate_user!, :only => [:new, :create]

	def index
		@classifieds = Classified.all
		@categories = Category.all
	end

	def new
		@classified = Classified.new
		@categories = Category.pluck(:name)
	end

	def show
		@classified = Classified.find(params[:id])
	end

	def create
		@classified = Classified.new(safe_classified_params)
		@classified.user = current_user
		@category = params[:category]

		# first_or_create - looks into table, if cat already exists returns, otherwise creates and returns
		@classified.category = Category.where(:name => @category.capitalize).first_or_create
		if @classified.save
			redirect_to classified_path(@classified)
		end
	end

	private

	def safe_classified_params
		return params.require(:classified).permit(:title, :description, :price, :image)
	end
end

stuff_finder/app/controllers/main_controller.rb
class MainController < ApplicationController
	
end

stuff_finder/app/helpers/application_helper.rb
module ApplicationHelper
end

stuff_finder/app/helpers/categories_helper.rb
module CategoriesHelper
end

stuff_finder/app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

stuff_finder/app/helpers/main_helper.rb
module MainHelper
end

stuff_finder/app/views/categories/show.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<h1><%= @category.name %></h1>
		<div class="span8">	
			<ul class="nav nav-list">
				<% @classifieds.each do |classified| %>
				<section class="well well-small">
					<li class="nav-header">
						<a href="<%= classified_path(classified) %>"><%= classified.title %> - <%= classified.price %></a>
					</li>
				</section>
				<% end %>
			</ul>	
		</div><!--end span-->
	</div><!--end row-->
</div><!--end container-->

stuff_finder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuffFinder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
	  <div class="navbar-inner">
	    <a class="brand" href="<%= root_path %>">StuffFinder</a>
	    <ul class="nav">
	      <li><a href="<%= classifieds_path %>">Browse Classifieds</a></li>
	      <li><a href="<%= new_classified_path %>">Post a Classified</a></li>
	    </ul>
	    <div style="float: right;">
		  <% if user_signed_in? %>
		    Hi, <%= current_user.email %>
		    <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
		  <% else %>
		    <a href="<%= new_user_session_path %>">Log In</a>
		    <a class="btn" href="<%= new_user_registration_path %>">Sign Up</a>
		  <% end %>
		</div>
	  </div>
	</div>
	<%= bootstrap_flash %>

<%= yield %>

</body>
</html>