portfolio/config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users
  root "main#index"
  get "main/about"
  get "main/contact"
  get "main/login"

  resources :projects
  resources :posts

  

end

portfolio/app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :project
end

portfolio/app/models/project.rb
class Project < ActiveRecord::Base
	validates :title, :description, presence:true

	has_many :images
	has_many :thumbnails

	def self.search_for(query)
		Project.where("title LIKE :query OR description LIKE :query OR category LIKE :query OR tag LIKE :query ORDER BY category ASC", :query => "%#{query}%")
	end

	def self.filter_for(cat)
		Project.where("category LIKE :cat AND featured = true ORDER BY category ASC", :cat => "%#{cat}%")
	end

	def self.get_filters
		projects = Project.all
		cats = []
		projects.each do |project|
			if !cats.include?(project.category)
				cats.push(project.category)
			end 
		end
		return cats
	end
end

portfolio/app/models/thumbnail.rb
class Thumbnail < ActiveRecord::Base
	belongs_to :project
end

portfolio/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

portfolio/app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
		@page_title = "Main page title"
		@subtitle = "Blah."
		@projects = Project.first(12)
	end

	def about
		@page_title = "About me"
		@subtitle = "Blah."
	end

	def contact
		@page_title = "Let's chat"
		@subtitle = "Blah."
	end
	def login
		@page_title = "Login to the admin area"
	end
end

portfolio/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@page_title = "Blog"

		@cats = Post.get_filters

		if params[:filter].present?
			@posts = Post.filter_for(params[:filter])
		else
			@posts = Post.all
		end
	end

	def new
	end

	def create
	end

	def edit
	end

	def show	
		@post = Post.find(params[:id])
		@page_title = @post.titlele 
	end

	def update
	end

	def destroy
	end

	private

	def safe_project_params
		return params.require(:posts).permit(:title, :description, :category, :main_image, :tn_images, :tags, :featured)
	e
end

portfolio/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :create, :destroy]

	def index
		@page_title = "Projects"
		@cats = Project.get_filters

		if params[:filter].present?
			@projects = Project.filter_for(params[:filter])
		else
			@projects = Project.all
		end
		
	end

	def new
		@page_title = "Create a new project"
		@project = Project.new
	end

	def create
		@project = Project.new(safe_project_params)

		if @project.save
			redirect_to projects_path
		else
			render :new
		end
	end

	def edit
		@project = Project.find(params[:id])
		@page_title = "Edit the project"
		@subtitle = @project.title
	end

	def show	
		@project = Project.find(params[:id])
		@page_title = "Projects"
		@subtitle = @project.title
		@main_image = Image.find(@project.main_image)
		@tn_image = Image.find(Thumbnail.find(@project.tn_images))
	end

	def update
		@project = Project.find(params[:id])
		@project.update(safe_project_params)

		redirect_to projects_path(@project)
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy

		redirect_to projects_path
	end

	private

	def safe_project_params
		return params.require(:project).permit(:title, :description, :category, :main_image, :tn_images, :tags, :featured)
	end
end

portfolio/app/controllers/users_controller.rb
class UsersController < ApplicationController
end

portfolio/app/helpers/admins_helper.rb
module AdminsHelper
end

portfolio/app/helpers/posts_helper.rb
module PostsHelper
end

portfolio/app/helpers/projects_helper.rb
module ProjectsHelper
end

portfolio/app/helpers/users_helper.rb
module UsersHelper
end

portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:action] %>">
	<div class="navbar">
	  <div class="navbar-inner">
	    <a class="brand" href="<%= root_path %>">Mark Centoni</a>
	    <ul class="nav">
	      <li><a href="<%= main_about_path %>">About</a></li>
	      <li><a href="<%= projects_path %>">Projects</a></li>
	      <li><a href="#">Blog</a></li>
	      <li><a href="<%= main_contact_path %>">Contact</a></li>
	    </ul>
	     <% if user_signed_in? %>
	    <p class="pull-right" style="margin-top:.5em">Hi, <%= current_user.email%> | <%= link_to "Log Out", destroy_user_session_path, :method => :delete %></p>
	    <% else %>
	    <a class="btn btn-primary pull-right" href="<%= new_user_registration_path %>">Sign Up</a>
	    <a class="btn pull-right" href="<%= new_user_session_path %>">Login</a>
	    <% end %>
	  </div>
	</div>

	<div class="content-wrapper">
		<%= yield %>
	</div><!--end content-wrapper-->
	
	<footer></footer>
</body>
</html>

portfolio/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<%= f.label :title, "Title" %>
	<%= f.text_field :title %>
	<%= f.label :description, "Description" %>
	<%= f.text_field :description %>
	<%= f.label :category, "Category" %>
	<%= f.text_field :category %>
	<%= f.label :main_image, "Primary Image" %>
	<%= f.text_field :main_image %>
	<%= f.label :tn_images, "Thumbnails" %>
	<%= f.text_field :tn_images %>
	<%= f.label :tags, "Tags" %>
	<%= f.text_field :tags %>
	<%= f.label :featured, "Featured on homepage" %>	
	<%= f.check_box :featured %>
	<%= f.submit "Save project", {:class =>"btn"} %>	
<% end %>

portfolio/app/views/projects/edit.html.erb
<%= render "main/hero" %>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3 offset4">
			<%= render "projects/form" %>
		</div><!--end span-->
	</div><!--end row-->
</div><!--end container-->

portfolio/app/views/projects/index.html.erb
<%= render "main/hero" %>
<!-- submenu for filtering, not functional yet -->
<div id="filters">
	<%= form_tag "/", :method => :get do %>
	<ul class="nav nav-pills">	
		<% @cats.each do |cat| %>
		<li><a href="#"><%= cat %></a><%= hidden_field_tag :filter, cat %></li>
		<% end %>
	</ul>
	<% end %>
</div>
<a class="btn" href="<%= new_project_path %>">+ Add a project</a>

<%= render "main/project_results" %>

portfolio/app/views/projects/new.html.erb
<%= render "main/hero" %>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3 offset4">
			<%= render "projects/form" %>
		</div><!--end span-->
	</div><!--end row-->
</div><!--end container-->

portfolio/app/views/projects/show.html.erb
<%= render "main/hero" %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3 offset4 <%= @project.category %>" data-featured="<%= @project.featured %>">
			<div class="cat-tab"><%= @project.category %></div>
			<img src="<%= image_path(@main_image.uri) %>">
			<h4><%= @project.title %></h4>
			<p><%= @project.description %></p>
			<p class="tags"><strong>Tags:</strong> <%= @project.tags %></p>
			<div id="project-tn" class="container-fluid">
				<% if @project.tn_images %>
					<img class="span3" src="<%= image_path(@tn_image.uri) %>">
				<% end %>
			</div><!-- end project thumbnails-->
			<% if user_signed_in? %>
				<a class="btn" href="<%= edit_project_path(@project) %>"><i class="eye-icon-open"></i> Edit Project</a>
				<%= button_to "Delete Project", project_path(@project), :method => :delete, :class => "btn btn-danger" %>
			<% end %>
			<a class="btn" href="<%= projects_path %>"><i class="icon-chevron-left"></i> Back to all projects</a>
		</div>
	</div>	
</div><!--end container-->